### ISSUE TITLE
Data review request

### ISSUE THREAD

**Issue by nhnt11** [mozilla/doh-resolver-usage-study#1]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

What fraction of users appearing to be on a Comcast network are actually using a Comcast DNS resolver?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?

We need to verify that the rate of mis-steering we're seeing is indeed explained by significant usage-rates of non-Comcast resolvers. Until we do, we can't proceed with the DoH rollout.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

There's no way to measure resolver usage without this new data. We need to measure on the nameserver side - so we had to set up a new domain and ship this code to query it.

4) Can current instrumentation answer these questions?

No.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.   

We are sending a single telemetry event with four extra keys. Three of the keys contain the results of looking up three domains:
1. doh.test - the canonical domain for CNAME-based discovery of network DoH endpoint
2. whoartthou - a domain that results in a well-known response when resolved via a Comcast resolver. Similar to doh.test - kind of a safety.
3. A uuid-subdomain of our canonical domain - <uuid>.firefox-resolver-usage-test.net

Each result is either the CNAME answer of the DNS lookup if it was present, or the list of IP addresses in the returned A records if present, or an empty string otherwise.

In addition to these three results, we also record the UUID generated by the client to use as the subdomain of the canonical domain.

This is Category 1 - technical data, because the lookups are only revealing information about the user's network environment. 

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

https://github.com/mozilla/doh-resolver-usage-study/blob/master/docs/TELEMETRY.md

7) How long will this data be collected?  Choose one of the following:

This data will only be collected during the study (currently tentatively scheduled to start on Aug 11 and run for a week or two)

8) What populations will you measure?

* Which release channels?

Release v79

* Which countries?

US only

* Which locales?

All

* Any other filters?  Please describe in detail below.

No.

9) If this data collection is default on, what is the opt-out mechanism for users?

Usual opt-out of studies in about:preferences

10) Please provide a general description of how you will analyze this data.

The UUIDs collected will be used to link request logs on our nameserver with the telemetry events. We'll then compare whether the requests we see from Comcast and non-Comcast resolvers on the nameserver end matches the events for which the doh.test result is and isn't the expected Comcast CNAME.

11) Where do you intend to share the results of your analysis?

Internally

12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:

Yes. The request logs on the DNS nameserver. The contents of the nameserver logs are the full domain that was requested along with the IP of the resolver that was used. This has been given a Trust sign-off. We are using Route53 as our provider.

**Comment by tdsmith** [comment]
Documentation:
- Please add the event category, method, value, and extra key names and value definitions to the telemetry documentation
- Please open a PR at https://github.com/mozilla/firefox-data-docs/blob/master/src/datasets/dynamic_telemetry.md to the telemetry documentation

> Each result is either the CNAME answer of the DNS lookup if it was present, or the list of IP addresses in the returned A records if present, or an empty string otherwise.

Arbitrary strings potentially contain sensitive data. How do you intend to use these values? Is it sufficient to compare them to the expected values, or do we need to collect these to maintain the value of the experiment?

**Comment by tdsmith** [comment]
> Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so: No

There is -- the nameserver logs.

This needs to be escalated to trust for this alone; can you give a complete description of the contents of the nameserver logs so we know what information we're associating with a client_id?

**Comment by nhnt11** [comment]
> Documentation:
> 
>     * Please add the event category, method, value, and extra key names and value definitions to the telemetry documentation

https://github.com/mozilla-extensions/doh-resolver-usage-study/pull/4

>     * Please open a PR at https://github.com/mozilla/firefox-data-docs/blob/master/src/datasets/dynamic_telemetry.md to the telemetry documentation

https://github.com/mozilla/firefox-data-docs/pull/540

> > Each result is either the CNAME answer of the DNS lookup if it was present, or the list of IP addresses in the returned A records if present, or an empty string otherwise.
> 
> Arbitrary strings potentially contain sensitive data. How do you intend to use these values? Is it sufficient to compare them to the expected values, or do we need to collect these to maintain the value of the experiment?

The data is coming from the external world though, so it's not arbitrary *user* data. I'd argue that it's sufficient to compare them to the expected values, but considering that part of the reason for doing this study is because we don't trust that the software is "free of defects", adding more logic here would create more surface for such defects. Quis custodiet ipsos custodes?

**Comment by nhnt11** [comment]
> > Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so: No
> 
> There is -- the nameserver logs.
> 
> This needs to be escalated to trust for this alone; can you give a complete description of the contents of the nameserver logs so we know what information we're associating with a client_id?

Updated OP. Trust sign-off has been granted. The contents of the nameserver logs are the full domain that was requested along with the IP of the resolver that was used.

**Comment by nhnt11** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
>     1. What questions will you answer with this data?
> 
> 
> What fraction of users appearing to be on a Comcast network are actually using a Comcast DNS resolver?
> 
>     1. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
> We need to verify that the rate of mis-steering we're seeing is indeed explained by significant usage-rates of non-Comcast resolvers. Until we do, we can't proceed with the DoH rollout.
> 
>     1. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> There's no way to measure resolver usage without this new data. We need to measure on the nameserver side - so we had to set up a new domain and ship this code to query it.
> 
>     1. Can current instrumentation answer these questions?
> 
> 
> No.
> 
>     1. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.
> 
> 
> We are sending a single telemetry event with four extra keys. Three of the keys contain the results of looking up three domains:
> 
>     1. doh.test - the canonical domain for CNAME-based discovery of network DoH endpoint
> 
>     2. whoartthou - a domain that results in a well-known response when resolved via a Comcast resolver. Similar to doh.test - kind of a safety.
> 
>     3. A uuid-subdomain of our canonical domain - .firefox-resolver-usage-test.net
> 
> 
> Each result is either the CNAME answer of the DNS lookup if it was present, or the list of IP addresses in the returned A records if present, or an empty string otherwise.
> 
> In addition to these three results, we also record the UUID generated by the client to use as the subdomain of the canonical domain.
> 
> This is Category 1 - technical data, because the lookups are only revealing information about the user's network environment.
> 
>     1. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> https://github.com/mozilla/doh-resolver-usage-study/blob/master/docs/TELEMETRY.md
> 
>     1. How long will this data be collected?  Choose one of the following:
> 
> 
> This data will only be collected during the study (currently tentatively scheduled to start on Aug 11 and run for a week or two)
> 
>     1. What populations will you measure?
> 
> 
>     * Which release channels?
> 
> 
> Release v79
> 
>     * Which countries?
> 
> 
> US only
> 
>     * Which locales?
> 
> 
> All
> 
>     * Any other filters?  Please describe in detail below.
> 
> 
> No.
> 
>     1. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> Usual opt-out of studies in about:preferences
> 
>     1. Please provide a general description of how you will analyze this data.
> 
> 
> The UUIDs collected will be used to link request logs on our nameserver with the telemetry events. We'll then compare whether the requests we see from Comcast and non-Comcast resolvers on the nameserver end matches the events for which the doh.test result is and isn't the expected Comcast CNAME.
> 
>     1. Where do you intend to share the results of your analysis?
> 
> 
> Internally
> 
>     1. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
> 
> 
> Yes. The request logs on the DNS nameserver. This has been given a Trust sign-off.

**Comment by nhnt11** [comment]
@tdsmith Let me know if your concerns have been addressed. If you feel strongly about not sending back the full DNS response and rather send a boolean indicating whether the response was the expected one, I can implement that, but I do feel like the team's position is to err on the side of having a bit extra information on this one.

If you approve, I will persist the final data-review doc in the OP into the docs/ directory.

**Comment by tdsmith** [comment]
The worst-case scenario is that someone's set up e.g. captiveportal.smith.family and we receive that value in telemetry. I think I agree that we do not _expect_ this value to contain personally identifiable information and it is in fact unlikely to contain personally identifiable information. If we're wrong, we'll have to clean it up.

Here are the Route 53 docs for query logs: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/query-logs.html#query-logs-format

For future travellers, that presently reads:

> Log format version: The version number of this query log. If we add fields to the log or change the format of existing fields, we'll increment this value.
> 
> Query timestamp: The date and time that Route 53 responded to the request, in ISO 8601 format and Coordinated Universal Time (UTC), for example, 2017-03-16T19:20:25.177Z. For information about ISO 8601 format, see the Wikipedia article ISO 8601. For information about UTC, see the Wikipedia article Coordinated Universal Time.
> 
> Hosted zone ID: The ID of the hosted zone that is associated with all the DNS queries in this log.
>
> Query name: The domain or subdomain that was specified in the request.
>
> Query type: Either the DNS record type that was specified in the request, or ANY. For information about the types that Route 53 supports, see Supported DNS record types.
>
> Response code: The DNS response code that Route 53 returned in response to the DNS query.
>
> Layer 4 protocol: The protocol that was used to submit the query, either TCP or UDP.
> 
> Route 53 edge location: The Route 53 edge location that responded to the query. Each edge location is identified by a three-letter code and an arbitrary number, for example, DFW3. The three-letter code typically corresponds with the International Air Transport Association airport code for an airport near the edge location. (These abbreviations might change in the future.) For a list of edge locations, see "The Route 53 Global Network" on the Route 53 Product Detail page.
> 
> Resolver IP address: The IP address of the DNS resolver that submitted the request to Route 53.
>
> EDNS client subnet: A partial IP address for the client that the request originated from, if available from the DNS resolver. For more information, see the IETF draft Client Subnet in DNS Requests.

These are all Category 1 collections, technical data.

**Comment by tdsmith** [comment]
data-review r+

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, in https://github.com/mozilla-extensions/doh-resolver-usage-study/blob/master/docs/TELEMETRY.md as referenced by the Firefox data docs. The Route 53 collection is described here.

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, the [Firefox telemetry opt-out](https://support.mozilla.org/en-US/kb/share-data-mozilla-help-improve-firefox) or by opting out of Normandy studies.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

n/a

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1, technical data.

5) Is the data collection request for default-on or default-off?

Default-on.

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No. The collection involves "UUIDs" that are used as a join key between the telemetry collection and the Route 53 collection but these are not "identifiers" in the usual sense; they are nonces that are discarded after telemetry is reported. They do not outlive the client_id. They are formatted as UUIDs for convenience only.

7) Is the data collection covered by the existing Firefox privacy notice?

Yes.

8) Does there need to be a check-in in the future to determine whether to renew the data?

No.

9) Does the data collection use a third-party collection tool?

Yes, Route 53. Trust and Legal have approved the third-party collection.
